### ISSUE TITLE
Minor: You are able to set radius to be negative

### ISSUE THREAD

**Issue by greycabb** [EZPick/EasyPick#26]
There is an issue where you are able to set radius to be negative.
___
1) Start at main page ( http://ezpick.herokuapp.com/ )

2) Click "Create" button

3) Set a valid meeting name, close out time, 30 minute duration, name, email, and schedule any dates.  But set Radius to a negative number such as "-300" and you will be allowed to submit it with the "Submit Your Meeting" button with this radius when it shouldn't be valid.

4) Now send an email invite for this submission to a valid email address.

5) In the email address provider for that email, open up the link.

6) Put valid inputs into this form, then click "Submit Response" it seems to always say "Submission failed! Please try again", which may be a problem with the radius being negative.

In console, I get the message "Failed to load resource: the server responded with a status of 404 (Not Found)", originating from "/api/response/create".

Browser: Google Chrome

**Comment by zmbc** [comment]
Thanks for pointing this out! Finding a location within -300 meters of somewhere is a bit challenging :laughing: 

The 404 issue, however, is not related. Turns out we had a routing issue in the production version of one of our controllers. This will be resolved by #27.

I've edited the issue title to only be about the negative radius.
