### ISSUE TITLE
[Minor] No indicator that meeting durations have to be 30-min intervals

### ISSUE THREAD

**Issue by lkhwa** [EZPick/EasyPick#32]
Really minor but mildly frustrating - the placeholder text says: "Type the duration of the meeting in minutes", but anything other than multiples of 30-min is invalid.

To reproduce:
1. Navigate to EasyPick page.
2. Fill in Meeting Name, Close-out Time, and Radius correctly.
3. Enter in a non-30-min meeting time, e.g. "20"
4. Fill in Name and Email fields.
5. Select Location Preferences.
6. The following warning should occur:
<img width="593" alt="screen shot 2017-06-04 at 11 51 21 pm" src="https://cloud.githubusercontent.com/assets/22458294/26773649/09012540-4981-11e7-884b-baeb72e50ff9.png">

Suggestion: you could either modify the placeholder text, or only let the user use the arrows to set the meeting duration :) 

*Was using Safari

**Comment by zmbc** [comment]
Thanks for the report!

Half the reason I didn't originally do this was because Chrome's warning is so much more helpful:
![chromewarning](https://cloud.githubusercontent.com/assets/13357648/26790656/5a8a8224-49c9-11e7-9463-35d8699f0553.png)

Looks like on some browsers, the user has no explanation of why the value is invalid. I think we'll update the placeholder text for this field.
