### ISSUE TITLE
[Minor] Schedule selection doesn't work on mobile.

### ISSUE THREAD

**Issue by BossJ** [EZPick/EasyPick#36]
Steps to reproduce:

1. Access app (ezpick.herokuapp.com) on mobile device or respond to email via mobile.

2. Attempt to select time slot from schedule.

**Comment by zmbc** [comment]
Thanks for the report!

Did you try holding down your press on the calendar? The way it currently works on mobile is that you have to hold down for 400ms to start selecting.

400ms is pretty long, but unfortunately there are some tradeoffs at work here. Click-and-drag is also the mobile gesture for scrolling, so this shorter this is, the more likely that someone would accidentally select when they meant to scroll.

**Comment by zmbc** [comment]
Closing as wontfix--even though I agree that the 400ms delay is a little slow for me, I haven't used a very large range of touch devices testing this, and FullCalendar selected 400ms as a default for a reason. Plus, since whatever number we'd select would be subjective, it'd be hard to say when/if this bug was definitely 'fixed.'
