### ISSUE TITLE
[Major] No Confirmation of Accepted/Scheduled Meetings

### ISSUE THREAD

**Issue by AlexBieg** [EZPick/EasyPick#38]
When scheduling a meeting and sending the email to another person who needs to attend, I received no confirmation that they had interacted with the email. By that I mean that when the recipient clicks "Submit Response" the person who created the meeting does not get a response. 

Reproduction Steps:
1. User1: Fill out the information required for a meeting.
2. User1: Send the meeting request to the email of User2.
3. User2: Receive the email and click on the link
4. User2: Fill out meeting response information and click "Submit Response"
5. User1: Notice that this user does not receive any notification of a response

**Comment by zmbc** [comment]
Thanks for the report!

If I understand you correctly, this is a feature request. We did not include a meeting-responded-to notification in our [requirements](https://github.com/EZPick/EasyPick/wiki/Requirements) (though we did include a page where user1--or anyone--can check who's already responded--see #25 for why that's not showing).

EasyPick is designed to be fundamentally asynchronous, which may be why you expected such a notification. In this issue's title, it says "Accepted/Scheduled Meetings," but a meeting is actually *not* scheduled when someone responds to it. It will stay open until its designated closeout time, so that more people can respond to it until then.

Does that explain the issue? If so, do you want to keep it open as a feature request?

**Comment by AlexBieg** [comment]
Oh okay I see. I was a little confused on the process of the application. I think you have sufficiently explained it for me to close the problem. Thanks!
