### ISSUE TITLE
[Minor] Units

### ISSUE THREAD

**Issue by DianaCondon** [EZPick/EasyPick#40]
There are no units given for radius distance or duration of time.

**Comment by zmbc** [comment]
Thanks for the report!

Units *are* given for the duration field, but only in the placeholder text (the text that disappears as soon as you start typing). We tried to do the same thing for the radius, but it has a default, which means that placeholder text is never visible unless you intentionally delete the default in order to view it. :laughing: 

Sounds like a good solution would be to put the units in the always-visible labels above the fields.
