### ISSUE TITLE
[Minor] Adjusting radius and time duration, too small of increments

### ISSUE THREAD

**Issue by DianaCondon** [EZPick/EasyPick#41]
would be much easier to have a drop down to choose from.

**Comment by zmbc** [comment]
Thanks for the report! I have some follow-up questions:
- Are you referring to the units themselves (meters and minutes) being too small? Or the inputs not allowing you to increment them in large enough chunks?
- Is this causing you to run into an error (like #32) or do you just mean that it's inconvenient to select the value you want?

**Comment by NgGeorge** [comment]
While a drop down menu may be nice to have, it is subjective in whether or not it adds any more actual usability our application. A drop down menu is not very practical for the radius, and the current option allows for it to be more precise. For the duration input, the drop down menu may become huge, which defeats the purpose of using it to save time. In addition, the drop down menu and the existing form input is functionally identical. Therefore, I feel that this issue is a non-failure that is not necessary to modify the application for. However, I appreciate you taking the time to bring this issue up with us.
