### ISSUE TITLE
No email sent/dead submission page.

### ISSUE THREAD

**Issue by jkuelz** [EZPick/EasyPick#47]
I tried creating and responding to an event using my actual emails and didn't get an email when I did either one. Also when I responded to an event it sent me to a submission page that was dead (unable to click anything to go anywhere/create a new event/view old events).
1. create an event
2. click "respond to meeting here"
3. the next page doesn't have any buttons for further action. Not clear whether clicking the back button will delete my submission or not.

**Comment by zmbc** [comment]
Thanks for the report!

Do you mind describing in more detail what you were expecting? You say that you didn't get emails when you created or responded to a meeting--we don't send emails in either of those situations. If you send an invite, those addresses are supposed to receive an email.

The link you clicked on in the email isn't supposed to allow you to create new meetings or view past ones, only respond to the one you've been invited to. After you respond, there are not supposed to be any links on the screen, just a dialog saying that the submission succeeded.

**Comment by jkuelz** [comment]
Oh okay! Thanks for the clarification, I guess it was my misunderstanding about the use-case of this service. I thought it was a more collaborative tool like "when to meet" rather than one owner that sees everything. I thought it might be useful to give invited users the option to create their own meetings once they are directed to your site via another invite. Not a major issue. Also whenever I enter my email I just assume it will be used for receiving an email at some point. But I understand now, thank you!

**Comment by zmbc** [comment]
It *is* intended to be a collaborative tool.

I think you may have been testing before #28 was merged. That should help somewhat, because now everyone is able to see who's responded to a meeting.

But what I'm seeing is that one of the core concepts of EasyPick isn't currently explained very well, which is that the meetings are scheduled asynchronously. When you set the "close-out time" in the meeting creation, you're setting when the meeting will actually be decided, and no action is taken before then. All the addresses you enter--as the creator of the meeting, and the people responding--*will* be sent an email at that "close-out time," saying when and where the meeting is scheduled for.

So it sounds like the issue you've run into is primarily a design issue, a lack of clarity about how the process works. If you can scope this issue down to something concrete and doable, we'd be happy to try to fix it. :smile:

**Comment by zmbc** [comment]
Closing as wontfix--this issue doesn't identify a bug, but a pretty complicated design problem. It's not clear how exactly to address this (if we did it correctly, it would probably involve user testing).
