### ISSUE TITLE
[Minor] No handle to go back to previously created Meetings

### ISSUE THREAD

**Issue by derryc09** [EZPick/EasyPick#48]
When users have created a meeting, if a user closes out the browser without copying the Meeting URL, then there's no way to go back to previously created meetings. 

**Steps to reproduce:**
1) CREATE a new meeting
2) Complete all fields. 
3) Close browser
4) Reopen EasyPick to see that there are no options to see previously created meetings. 

**Recommendation**:
Perhaps it would be easier if an email confirmation would be sent to the user's inbox so that the URL is not completely LOST if not taken note of.

**Comment by zmbc** [comment]
Thanks for the report!

Yes, it's a little problematic that these things can be lost so easily. I don't think we want to have user accounts (because EasyPick is intended to be so simple) but your suggestion of a confirmation email sounds good to me. I'm marking as an enhancement because this wasn't in the requirements.
